spring:
  cloud:
    gateway:
      routes:
        - id: notification-service
          uri: http://localhost:8083  # Replace with your notification service address
          predicates:
            - Path=/NOTIFICATION-SERVICE/**  # Path match for routing
          filters:
            - RewritePath=/NOTIFICATION-SERVICE/(?<remaining>.*), /${remaining}  # Rewrite the path
